# Generated by Django 5.1.4 on 2024-12-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='comision',
        ),
        migrations.RenameField(
            model_name='entregable',
            old_name='fechaDeEntrega',
            new_name='fecha_de_Entrega',
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(max_length=30),
        ),
    ]
