# Generated by Django 5.1.4 on 2024-12-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laApp', '0002_rename_camada_curso_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
