# Generated by Django 5.1.4 on 2025-01-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laApp', '0005_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
    ]
