# Generated by Django 5.1.4 on 2025-01-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laApp', '0006_rename_fecha_publicacion_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='texto',
            field=models.TextField(default=''),
        ),
    ]
